# Identificadores únicos (sacados de la interfaz de SonarQube)
sonar.projectKey=PaginaWeb
sonar.projectName=PaginaWeb
sonar.projectVersion=1.0

# Ubicación del código fuente
sonar.sources=src

# Exclusiones críticas: No queremos analizar librerías ni código de test para la deuda técnica principal
sonar.exclusions=node_modules/**, dist/**, build/**, **/*.test.js, **/*.spec.js, **/*.test.tsx, **/*.spec.tsx, src/reportWebVitals.js, src/setupTests.js

# Configuración del servidor (ajusta el puerto si lo cambiaste)
sonar.host.url=http://localhost:9000

# El token que generaste en la interfaz de SonarQube
sonar.login=sqp_8515511f31aae0e8e8f925362a82e1fee8d3dd29

# Codificación
sonar.sourceEncoding=UTF-8